version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/dockerfiles"
    schedule:
      interval: daily
  - package-ecosystem: pip
    directory: "/external/price_server"
    schedule:
      interval: daily
    ignore:
      - dependency-name: importlib-metadata
        update-types: ["version-update:semver-major"]
    groups:
      pylint:
        patterns:
          - "pylint"
          - "astroid"
