version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: "/dockerfiles"
    sechedule:
      interval: daily

