apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.cart.serviceName }}
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: cart
