kind: Job
apiVersion: batch/v1
metadata:
  name: dataseed
spec:
  template:
    spec:
      containers:
        - name: dataseed
          image: "{{ .Values.db.dataseed.image.repository }}:{{ .Values.db.dataseed.image.tag }}"
          imagePullPolicy: {{ .Values.db.dataseed.image.pullPolicy }}
          env:
            - name: DB_ADDRESS
              value: {{ .Values.db.address }}
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: {{ .Values.db.rootPassword }}
      restartPolicy: OnFailure
