apiVersion: apps/v1
kind: Deployment
metadata:
  name: price
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price
  template:
    metadata:
      labels:
        app: price
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: {{ .Values.db.address }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.db.database }}
            - name: DB_USER
              value: {{ .Values.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
            - name: AUTH_TYPE
              value: scram-sha-256
        - name: price
          image: "{{ .Values.price.image.repository }}:{{ .Values.price.image.tag }}"
          imagePullPolicy: {{ .Values.price.image.pullPolicy }}
          args:
            - "-b"
            - "0.0.0.0:{{ .Values.price.port }}"
            - "--log-level"
            - "debug"
          env:
            - name: DB_ADDRESS
              value: localhost
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: {{ .Values.db.database }}
            - name: DB_USER
              value: {{ .Values.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
            - name: HOST_IP
              value: "{{ .Values.otel-receiver }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
