apiVersion: apps/v1
kind: Deployment
metadata:
  name: trafficgen
spec:
  replicas: {{ .Values.trafficgen.replicas }}
  selector:
    matchLabels:
      app: trafficgen
  template:
    metadata:
      labels:
        app: trafficgen
    spec:
      containers:
        - name: trafficgen
          image: "{{ .Values.trafficgen.image.repository }}:{{ .Values.trafficgen.image.tag }}"
          imagePullPolicy: {{ .Values.trafficgen.image.pullPolicy }}
          args: 
            - "-c"
            - "{{ .Values.trafficgen.concurrency }}"
            - "--cart-url"
            - "{{ .Values.cart.serviceName }}:{{ .Values.cart.port }}"
            - "--users-url"
            - "{{ .Values.user.serviceName }}:{{ .Values.user.port }}"
