apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.user.serviceName }}
  labels:
    release: prometheus
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      app: user
