apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: pgbouncer
          image: edoburu/pgbouncer:latest
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: {{ .Values.db.address }}
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: {{ .Values.db.database }}
            - name: DB_USER
              value: {{ .Values.db.user }}
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
            - name: AUTH_TYPE
              value: scram-sha-256
        - name: user
          image: "{{ .Values.user.image.repository }}:{{ .Values.user.image.tag }}"
          imagePullPolicy: {{ .Values.user.image.pullPolicy }}
          args: 
            - "-p"
            - "{{ .Values.user.port }}"
            - "--db-address"
            - localhost
            - "--db-user"
            - "{{ .Values.db.user }}"
            - "--otel-receiver"
            - "{{ .Values.otel-receiver }}"
          env:
            - name: DB_PASSWORD
              value: {{ .Values.db.password }}
          ports:
            - name: http
              containerPort: {{ .Values.user.port }}
              protocol: TCP
