apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  image: "{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}"
  mode: statefulset
  targetAllocator:
    enabled: true
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        release: prometheus
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug
      otlp:
        endpoint: jaeger-collector:4317
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9000"

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging,otlp]
        metrics:
          receivers: []
          processors: []
          exporters: [prometheus]
