cart:
  serviceName: cart
  image:
    repository: localhost:5000/otel-shopping-cart-cart
    tag: latest
    pullPolicy: Always
  port: 80

user:
  serviceName: user
  image:
    repository: localhost:5000/otel-shopping-cart-users
    tag: latest
    pullPolicy: Always
  port: 80

price:
  serviceName: price
  image:
    repository: localhost:5000/otel-shopping-cart-price
    tag: latest
    pullPolicy: Always
  port: 80

db:
  image:
    repository: postgres
    tag: 16
    pullPolicy: Always
  address: db
  port: 5432
  database: otel_shopping_cart
  user: shoppingcartuser
  password: secretdbpassword123
  rootPassword: localdb123

  dataseed:
    image:
      repository: localhost:5000/otel-shopping-cart-dataseed
      tag: latest
      pullPolicy: Always

collector:
  image:
    repository: localhost:5000/otel-shopping-cart-collector
    tag: latest
    pullPolicy: Always
