FROM golang:1.22@sha256:7b297d9abee021bab9046e492506b3c2da8a3722cbf301653186545ecc1e00bb AS builder
LABEL org.opencontainers.image.source https://github.com/trstringer/otel-shopping-cart
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o users ./cmd/users

FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
COPY --from=builder /var/app/users /var/app/users
ENTRYPOINT ["/var/app/users"]
