FROM golang:1.22@sha256:7b297d9abee021bab9046e492506b3c2da8a3722cbf301653186545ecc1e00bb AS builder
LABEL org.opencontainers.image.source https://github.com/trstringer/otel-shopping-cart
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o cart ./cmd/cart

FROM alpine:3.13@sha256:469b6e04ee185740477efa44ed5bdd64a07bbdd6c7e5f5d169e540889597b911
COPY --from=builder /var/app/cart /var/app/cart
ENTRYPOINT ["/var/app/cart"]
