FROM golang:1.22@sha256:6a02cc10cb339f7fdb0feace29e0db457f0b84641cd030a3ada30964390af625 AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o trafficgen ./cmd/trafficgen

FROM alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b
LABEL org.opencontainers.image.source https://github.com/trstringer/manual-approval
COPY --from=builder /var/app/trafficgen /var/app/trafficgen
ENTRYPOINT ["/var/app/trafficgen"]
