FROM golang:1.22@sha256:ef61a20960397f4d44b0e729298bf02327ca94f1519239ddc6d91689615b1367 AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o users ./cmd/users

FROM alpine:3
COPY --from=builder /var/app/users /var/app/users
ENTRYPOINT ["/var/app/users"]
