FROM golang:1.18 AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o users ./cmd/users

FROM alpine:3
COPY --from=builder /var/app/users /var/app/users
ENTRYPOINT ["/var/app/users"]
