FROM golang:1.18 AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o interrupter ./cmd/interrupter

FROM alpine:3
COPY --from=builder /var/app/interrupter /var/app/interrupter
ENTRYPOINT ["/var/app/interrupter"]
