FROM golang:1.21@sha256:7b575fe0d9c2e01553b04d9de8ffea6d35ca3ab3380d2a8db2acc8f0f1519a53 AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o interrupter ./cmd/interrupter

FROM alpine:3
COPY --from=builder /var/app/interrupter /var/app/interrupter
ENTRYPOINT ["/var/app/interrupter"]
