FROM ubuntu:24.04@sha256:562456a05a0dbd62a671c1854868862a4687bf979a96d48ae8e766642cd911e8
LABEL org.opencontainers.image.source https://github.com/trstringer/manual-approval
WORKDIR /var/app
COPY ./database/setup.sql /var/app
RUN apt update && apt install -y postgresql-client
CMD ["/bin/bash", "-c", "PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -d postgres -h $DB_ADDRESS -c 'DROP DATABASE IF EXISTS otel_shopping_cart;' && PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -d postgres -h $DB_ADDRESS -c 'CREATE DATABASE otel_shopping_cart;' && PGPASSWORD=$DB_PASSWORD psql -U $DB_USER -d otel_shopping_cart -h $DB_ADDRESS -f setup.sql"]
