FROM golang:1.22@sha256:39595615e0bbd02679d75735ede0b1c20d61d587e53c95fae0cf39a3fb1c813d AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o interrupter ./cmd/interrupter

FROM alpine:3
COPY --from=builder /var/app/interrupter /var/app/interrupter
ENTRYPOINT ["/var/app/interrupter"]
