FROM golang:1.22@sha256:39595615e0bbd02679d75735ede0b1c20d61d587e53c95fae0cf39a3fb1c813d AS builder
COPY . /var/app
WORKDIR /var/app
RUN CGO_ENABLED=0 go build -o cart ./cmd/cart

FROM alpine:3
COPY --from=builder /var/app/cart /var/app/cart
ENTRYPOINT ["/var/app/cart"]
