FROM ubuntu:latest
LABEL org.opencontainers.image.source https://github.com/trstringer/manual-approval
COPY \
    ./external/price_server \
    /var/app/
WORKDIR /var/app
RUN apt-get update && apt-get install -y libpq-dev python3-pip build-essential && pip install -r ./requirements.txt
ENTRYPOINT ["gunicorn", "app:app"]
