# FROM alpine:3
FROM ubuntu:latest
COPY \
    ./external/price_server \
    /var/app/
WORKDIR /var/app
# RUN apk add --no-cache --update py-pip python3 && \
#     pip install -r ./requirements.txt
RUN apt-get update && apt-get install -y libpq-dev python3-pip build-essential && pip install -r ./requirements.txt
ENTRYPOINT ["gunicorn", "app:app"]
